### ISSUE TITLE
Action scope

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder-release-tools#11]
Actions submit `CheckRun`s for different checks. Those `CheckRun`s owned by a commit, not by a PR. Therefore, when a new commit gets (force-)pushed, the `CheckRun`s that reports the result of this action is lost.

Could we retrieve the previous `CheckRun`s from the old commit `on: pull-request: [synchronize]` and push them to the new commit? I think the hard part here will be knowing the sha of the commit that holded the previous checks.

In this case the pseudo code would be:
```
on: pull-request: open
- create CheckRun with "in_progress" status
- perform the checks
- update CheckRun with results

on: pull-request: edit
- update CheckRun with "in_progress" status
- perform the checks
- update CheckRun with results

on: pull-request: synchronize
- find the previous commit hash
- create CheckRun with same result as CheckRun @ previous commit
```

**Comment by DirectXMan12** [comment]
yep, we need synchronize.  I think it's probably fine to just re-run the run on synchronize though -- it's not too expensive.
