### ISSUE TITLE
Allow vX instead of release-X for release branches

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/kubebuilder-release-tools#29]
KB wants to be go-getable, which means it needs to follow Go semver, which means release branches should be `vX`.  Instead of having to maintain separate `release-X` and `vX` branches, we should just make the release tooling accept either.

**Comment by Adirio** [comment]
/remove-lifecycle stale

I think this branch names may conflict with tags used for releases. I think it may be more interesting for `vX` tags to point to the latest stable release of `release-X`. For example, in kubebuilder `v2` would point to tag `2.3.2` currently.
