### ISSUE TITLE
Wrong link has been used in the notes generated

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder-release-tools#37]
See the following link in KB releases: https://github.com/kubernetes-sigs/kubebuilder/releases

<img width="462" alt="Screen Shot 2021-02-18 at 09 27 56" src="https://user-images.githubusercontent.com/7708031/108336110-9a8a8080-71cb-11eb-8699-fa5001b7dfed.png">

Note that the link is: https://github.com//releases/v3.0.0-alpha.1 when IMO it should be:  https://github.com/kubernetes-sigs/kubebuilder/compare/v3.0.0-alpha.1...v3.0.0-beta.0

I mean, a compare from the previous release to the current one: `https://github.com/kubernetes-sigs/kubebuilder/compare/<previoustag>...<newtag>`

**Comment by camilamacedo86** [comment]
c/c @Adirio

**Comment by Adirio** [comment]
IMO this are two things:
1. Fixing the link generation: not sure which repo's fault it is. I provided more info related to this in https://github.com/kubernetes-sigs/kubebuilder/issues/2031
2. Changing the link to a comparison one.

Related to the link change, I would say that we can provide that link in the word "changes" and leave the link in the version tag point to the that version's release.
