### ISSUE TITLE
Allow "tag prefixes" in PR titles

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/kubebuilder-release-tools#43]
Hey folks,

we are using kubebuilder-release-tools in ClusterAPI to validate PR titles. Overall it works great, but I wonder if it would be possible to allow "tag prefixes" in PR titles.

For example, a regular valid PR title looks like this: `✨ Upgrade to Kubernetes 1.23.3 in Quickstart and CI`.

If the PR title:
* would contain a `[WIP]` prefix it would be invalid (`[WIP] ✨ Upgrade to Kubernetes 1.23.3 in Quickstart and CI`).
* would contain a `[release-1.1]` prefix it would be invalid (`[release-1.1] ✨ Upgrade to Kubernetes 1.23.3 in Quickstart and CI`)
    * Note: the cherry-pick bot adds the `[<branch>] ` prefix automatically on cherry-pick PRs

**Comment by sbueringer** [comment]
@vincepri @camilamacedo86 What do you think?

(cc @CecileRobertMichon @fabriziopandini)

**Comment by vincepri** [comment]
The above pushes the problem of cleaning up the titles (for branch prefixes at least) to the release authors, is that something we'd want to do for each backport?

**Comment by sbueringer** [comment]
> The above pushes the problem of cleaning up the titles (for branch prefixes at least) to the release authors, is that something we'd want to do for each backport?

I think we can make this behavior optional and for CAPI only enable it on the main branch *after* we adjusted our release notes generation tool to be able to handle that.

Currently, we have to run `retitle` on **every** cherry-pick PR and I think it would be good to get rid of that at some point.

**Comment by CecileRobertMichon** [comment]
I'm +1 on this

> I think we can make this behavior optional and for CAPI only enable it on the main branch after we adjusted our release notes generation tool on main to be able to handle that.

+1, the release notes tool should automatically get rid of the prefixes

It would be good to not have to retitle every cherry pick + being able to see at a glance that a PR is a cherry pick (github has a branch label but it's not as obvious)

**Comment by fabriziopandini** [comment]
+1 for WIP
I can see the value also in having a branch prefix, +1 for this as well
