### ISSUE TITLE
Looking for a way to allow a new emoji 🚀

### ISSUE THREAD

**Issue by mjlshen** [kubernetes-sigs/kubebuilder-release-tools#54]
https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/482e922abce8082469453f384cad12686cf3210d/notes/common/prefix.go#L94-L118 currently maintains a hardcoded list of PR prefixes. In cluster-api, we use this GitHub action and would like to use a new emoji 🚀 to denote the PR as a release PR.

Is there interest in onboarding a new emoji into this GitHub Action, or alternatively I can look into submitting a PR to allow consumers of this GitHub Action to specify a list of additional emoji's that are allowed? The benefits of this approach would be that we do not force other users of this GitHub Action to also accept the 🚀 emoji.

**Comment by furkatgofurov7** [comment]
@vincepri @camilamacedo86 @varshaprasad96 hey folks sorry for tagging directly, but can someone take a look at the above request and help taking it further if it makes sense to you? Thanks!
