### ISSUE TITLE
MIgrate build and promotion of images from Kubebuilder GCP

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder-release-tools#60]
We are using the project to generate the image gcr.io/kubebuilder/pr-verifier:$TAG_NAME. This image, generated by the project https://github.com/kubernetes-sigs/kubebuilder-release-tools, is used in the CI to verify PR emojis for release notes.

The goal of this one is move forward and use he regular image promotion / k8s infra to promote those images.

**Be aware that  the current images will be unavailable from March 18, 2025.**

Motivation: https://github.com/kubernetes/k8s.io/issues/2647 and https://github.com/kubernetes-sigs/kubebuilder/discussions/3907

**Comment by camilamacedo86** [comment]
Following some important info to help out on this one
- We might can use the artefacted created already: https://github.com/kubernetes/k8s.io/pull/4586
- We need to update the contact point with the owners of this repo: https://github.com/kubernetes/k8s.io/pull/4586/files#diff-c6a289a0bdff1385e8310aaa57be9a90137e1cb414e654ea2334c1a08af89c9eR4-R7
- It will be required add the JOB to build the image in the e2e infra that would be something like: https://github.com/kubernetes/test-infra/pull/29351/files
- In this repo will be required to add a build.sh I think . Something that will trigger the job when a new tag is generated. Just to have an idea (the changes here does not work for other reason, we need to use image from upstream projects outside of kuberntes-sig): https://github.com/kubernetes-sigs/kubebuilder/pull/3362/files

**Comment by TAM360** [comment]
@camilamacedo86 I am interested in working on this task.

**Comment by camilamacedo86** [comment]
It seems out of the scope but we probably need add more people in : https://github.com/kubernetes/k8s.io/pull/4586/files#r1682542243

(Just adding here for now)

**Comment by camilamacedo86** [comment]
@TAM360 

Thank you a lot for your terrfic work and help us understand how would be the process moving forward.
This project does not do too much today and has no maintainers

Therefore, due the fact of this image only check the PR title it seems that make no sense we need to have the infrastructure for each and have a process where we need to build image in stage and then publish for prod. It seems that we can create a shell script or let people use the same implementation in other ways.

So, lets close this one 

@sbueringer ^ +1 for your thought that the work is not valid here.

**Comment by sbueringer** [comment]
Sounds reasonable to me
